version: 2

jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install -y sudo iproute2
            sudo apt-get install -y python3-pip libpython2-dev git libssl-dev libpq-dev gcc
            sudo pip install ansible\==5.7.0 psycopg2
      - checkout
      - run:
          name: Execute ansible playbook
          # Test without -K option to make it non-interactive
          command: ansible-playbook -i hosts site.yml

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "00 1 * * 1" # Every Monday at 1:00(UTC)
          filters:
            branches:
              only:
                - master
    jobs:
      - build